<?php
defined('ORDER_PAYMENT_STATUS_PROCESSING') or define('ORDER_PAYMENT_STATUS_PROCESSING', 1);
defined('ORDER_PAYMENT_STATUS_DONE') or define('ORDER_PAYMENT_STATUS_DONE', 2);
defined('ORDER_PAYMENT_STATUS_CANCEL') or define('ORDER_PAYMENT_STATUS_CANCEL', 3);
defined('ORDER_PAYMENT_STATUS_LIST') or define('ORDER_PAYMENT_STATUS_LIST', [
    ORDER_PAYMENT_STATUS_PROCESSING => 'Chưa Thanh Toán',
    ORDER_PAYMENT_STATUS_DONE => 'Đã Thanh Toán',
    ORDER_PAYMENT_STATUS_CANCEL => 'Huỷ Thanh Toán'
]);
defined('ORDER_DELIVERY_STATUS_PROCESSING') or define('ORDER_DELIVERY_STATUS_PROCESSING', 1);
defined('ORDER_DELIVERY_STATUS_DONE') or define('ORDER_DELIVERY_STATUS_DONE', 2);
defined('ORDER_DELIVERY_STATUS_CANCEL') or define('ORDER_DELIVERY_STATUS_CANCEL', 3);
defined('ORDER_DELIVERY_STATUS_LIST') or define('ORDER_DELIVERY_STATUS_LIST', [
    ORDER_DELIVERY_STATUS_PROCESSING => 'Đang giao hàng',
    ORDER_DELIVERY_STATUS_DONE => 'Đã giao hàng',
    ORDER_DELIVERY_STATUS_CANCEL => 'Huỷ đơn hàng'
]);
defined('ORDER_PAYMENT_METHOD_VNPAY') or define('ORDER_PAYMENT_METHOD_VNPAY', 1);
defined('ORDER_PAYMENT_METHOD_MOMO') or define('ORDER_PAYMENT_METHOD_MOMO', 2);
defined('ORDER_PAYMENT_METHOD_COD') or define('ORDER_PAYMENT_METHOD_COD', 3);
defined('ORDER_PAYMENT_METHOD_LIST') or define('ORDER_PAYMENT_METHOD_LIST', [
    ORDER_PAYMENT_METHOD_VNPAY => 'Thanh toán VNPay',
    ORDER_PAYMENT_METHOD_MOMO => 'Thanh toán Momo',
    ORDER_PAYMENT_METHOD_COD => 'Thanh toán Khi Giao hàng'
]);
